### PR TITLE
Display Vidarr tracing and allow sorting by trace in the UI

### PR DESCRIPTION
**Pull request by apmasell**
* Allow actions to be sorted in the UI
* Display tracing on Vidarr submission actions

- [X] Updates Changelog
- [X] Updates developer documentation

### CODE REVIEW

**Comment by avarsava** [comment]
UI has a line break really early in the options? 
image

**Comment by apmasell** [comment]
And that's bad? Maybe it's time to bring the Windows ribbon UI to Shesmu.  I don't really know how to organize these options anymore.

**Comment by avarsava** [comment]
Why do all the built-in vidarr sorts start with 'Custom'?

**Comment by avarsava** [comment]
vidarr-attempt is clear, but what is vidarr-waiting sorting by?

**Comment by avarsava** [comment]
Should this PR include an update to ops-guide.md?

**Comment by apmasell** [comment]
`Custom` is because they're based on the actions, not a Shesmu built-in. `vidarr-waiting` is how long a Vidarr job has been waiting for resources.

**Comment by avarsava** [comment]
> Custom is because they're based on the actions, not a Shesmu built-in. 

That's very unclear to me because _we_ didn't define the sort (ie a custom sort). It's defined inside the vidarr plugin - I'd say this is a Shesmu builtin. I'm not sure why the user needs to know the distinction, but if they do, could this be 'Plugin' or something?

**Comment by apmasell** [comment]
Sure. `Plugin`? Or something else?

**Comment by avarsava** [comment]
Plugin works

**Comment by avarsava** [comment]
I sorted my actions by vidarr-attempt, most have 0 attempt and one has 1. the 1-attempt action is in the middle of the list. Am I not understanding how this feature should work?

**Comment by apmasell** [comment]
Are they on the same page? This will have stability problems across pages, which has always been the case.

**Comment by avarsava** [comment]
Same page, I only have 1 page's worth of actions

**Comment by apmasell** [comment]
I don't know then. I didn't have this problem in testing.

**Comment by apmasell** [comment]
Hmm, the `vidarr-attempt` is being populated from the _request_. If the action has not reattempted the request, it will be zero. However, if the workflow run has been reattempted, then the attempt numbers in the _response_ can be higher.

**Comment by apmasell** [comment]
Okay, rebase and I've changed the `vidarr-attempt` in a way that should better match intuition.

**Review by rnaioicr — APPROVED** [review]

**Review by avarsava — APPROVED** [review]
Makes more sense, thank you!

**Pull request merged**
