### PR TITLE
[GP-3619] Lock down tsc version in README

### PR DESCRIPTION
**Pull request by avarsava**
JIRA Ticket: GP-3619

- [n/a] Updates Changelog
- [n/a] Updates developer documentation

### CODE REVIEW

**Review by callunity — APPROVED** [review]

**Review by djcooke — APPROVED** [review]
Installing this as a dev dependency in the project rather than recommending global install could both enforce the version used and simplify dev setup

**Comment by avarsava** [comment]
> Installing this as a dev dependency in the project rather than recommending global install could both enforce the version used and simplify dev setup

I don't know if typescript has something like python's virtual environments, how would i do this?

**Comment by djcooke** [comment]
> > Installing this as a dev dependency in the project rather than recommending global install could both enforce the version used and simplify dev setup
> 
> How would i do this?

It looks like Shesmu doesn't really use npm right now, so it would require some setup. You'd need a `package.json` with typescript as a dev dependency. You could then run tsc via npx.

You could also take it a step farther and use exec-maven-plugin to do your ts build automatically as part of the Maven build.

**Comment by avarsava** [comment]
> It looks like Shesmu doesn't really use npm right now, so it would require some setup. You'd need a `package.json` with typescript as a dev dependency. You could then run tsc via npx.
> 
> You could also take it a step farther and use exec-maven-plugin to do your ts build automatically as part of the Maven build.

We have a ticket (GP-3477) for using exec-maven-plugin but it's marked as requiring tsc 4.4, which in turn needs development work because the front end doesn't compile with that version. 
This will all be resolved when we get around to that ticket, sound OK?

**Pull request merged**
