### PR TITLE
Add search import button

### PR DESCRIPTION
**Pull request by apmasell**
This was accidentally removed during the UI redesign.

### CODE REVIEW

**Comment by avarsava** [comment]
I see there's an Upload button, but what do I upload? I can't seem to find an Export button

**Comment by apmasell** [comment]
Oh, it's on the lower toolbar: _Export Search_ and then either _To Clipboard_, _To Clipboard for Ticket_, or _To File_ will be a format this can read. I will add some text for this though.

**Comment by avarsava** [comment]
> Oh, it's on the lower toolbar: _Export Search_ and then either _To Clipboard_, _To Clipboard for Ticket_, or _To File_ will be a format this can read. I will add some text for this though.

Sorry, where is the lower toolbar? 
image

**Comment by apmasell** [comment]
I think there's another bug. It only shows if there are any actions, which isn't quite right. I'll fix that.

**Comment by apmasell** [comment]
Fixed. It should display now. I didn't notice because my testing instance has some fake actions in it.

**Comment by avarsava** [comment]
image
It does display, but I think it's incorrect

**Comment by avarsava** [comment]
Also, probably unrelated, but when I save a search, then leave Shesmu and come back, and select my search from the dropdown, the filters bar is empty, is that intentional?

**Comment by apmasell** [comment]
Yes, that is intentional. The search is the selected search + additional filters, so once you save it, that's not visible.

**Pull request merged**
