### PR TITLE
Keep menus open when clicked

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by apmasell** [comment]
It's not intentional. I've changed it so the menu will stay open once you select an item (any item). I also changed it so if you mouse over another add button, it will close the selected menu, even if you clicked it open.

**Comment by callunity** [comment]
It looks like only the "Add" menus are 'sticky'; can this be added to the "Ago" and "type of text search" menus too?

**Comment by apmasell** [comment]
Okay. It's consistent now.

**Comment by callunity** [comment]
I dunno about "need", but it was unexpected to have different behaviour for different dropdowns!

**Pull request merged**
