### PR TITLE
Gp 4415.add cardea detailed case input format

### PR DESCRIPTION
**Pull request by grapigeau**
JIRA Ticket: https://jira.oicr.on.ca/browse/GP-4415

- [x] Updates Changelog
- [ ] Updates developer documentation

### CODE REVIEW

**Comment by avarsava** [comment]
Detailed summaries seem to differ from the original summaries by three columns - why not expand the existing format?

**Comment by grapigeau** [comment]
> Detailed summaries seem to differ from the original summaries by three columns - why not expand the existing format?
The eventual goal is to deprecate and replace the existing case_summary but the understanding is this will not be an instant transition.
The meeting notes linked in the ticket give a little more info: https://wiki.oicr.on.ca/display/GSI/Review+of+New+Case+Format+for+Shesmu

**Comment by avarsava** [comment]
If none of the columns in use in the case_summary format are changing, then adding new columns to the format won't affect production olives at all. I'm not sure I understand the concern

**Comment by grapigeau** [comment]
> If none of the columns in use in the case_summary format are changing, then adding new columns to the format won't affect production olives at all. I'm not sure I understand the concern

We decided not to include limsIds (list) in Cardea since it's duplicate information so it's not just an addition of columns.

**Comment by avarsava** [comment]
What do you mean by limsIds not being in cardea? Where do they come from then?

**Comment by grapigeau** [comment]
> What do you mean by limsIds not being in cardea? Where do they come from then?

I mean the value `"limsIds": [
      "string"
    `],`` which is present at the /shesmu-cases endpoint is not available at the /shesmu-detailed-cases endpoint. I should've specified new Cardea endpoint, not "Cardea."

**Comment by mlaszloffy** [comment]
> Detailed summaries seem to differ from the original summaries by three columns - why not expand the existing format?

caseStatus logic is also changing.

**Review by mlaszloffy — APPROVED** [review]

**Review by avarsava — APPROVED** [review]

**Pull request merged**
