### PR TITLE
Add Nothing keyword to create empty optional

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by callunity** [comment]
There's already the `nothing` action, and I wonder if these could be confused. Would `Empty` work as an alternative name for the empty optional?

**Comment by apmasell** [comment]
Oh, yikes. I forgot. Internally, empty generally refers to an empty list. I think I'd rather rename the `nothing` action to `do_nothing`, `inaction` or something like that.

**Comment by callunity** [comment]
Renaming makes sense to me. I'm a fan of `do_nothing`

**Comment by apmasell** [comment]
To match the rest of the JSON action names with dashes. :sweat:

**Pull request closed without merging**
